Create quiz4.md
ReDI-School/js-berlin-2019-fall pull request #7
Opened 2019-09-14 20:36 UTC by sevtapim

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +console.log( johnsAge === janesAge);
```suggestion
console.log(johnsAge === janesAge);
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +console.log( parseInt(johnsAge) === janesAge);
```suggestion
console.log(parseInt(johnsAge) === janesAge);
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +Valid but not what we had in mind. We expected to see 30 but got 1020 instead. Because, JavaScript does string concatenation when one of the operands has string type. To fix this issue, we need to us
```suggestion
Valid but not what we had in mind. We expected to see 30 but got 1020 instead. JavaScript does string concatenation when one of the operands is a string type. To fix this issue, we need to use the `parseInt` function, which converts a string value into a number value.
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +Valid, but if we want the text content of second paragraph element using its id, it won't work. Because in an HTML document, you must have unique ids for your elements.
```suggestion
Valid, but if we want the text content of second paragraph element using its id, it won't work. In an HTML document, you must have unique ids for your elements.
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +Valid. But not a good practice. Because here we are using the age variable first to access the input element which is of type object, and then we are using the same variable to access the content of
```suggestion
Valid. But not a good practice. Here we are using the age variable first to access the input element which is of type object, and then we are using the same variable to access the content of the value attribute which is of type string. Using the same variable name for two different objects is not a good idea. Always use separate variable names for different objects.
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +Now we have a **"go-to person"** (nameElement) for making enquires about our object. This input element has two attributes, id and type. How can we get the content of a specific attribute. When an ob
```suggestion
Now we have a **"go-to person"** (`nameElement`) for making enquires about our object. This input element has two attributes, id and type. How can we get the content of a specific attribute. When an object contains many values, we use predefined names to access individual values and we use a **.** operator to do that. A predefined name and a value together is called a **property** of an object. So in our example, we use the following code in JavaScript:
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +messageElement.textContent; // No messages
```suggestion
messageElement.textContent; // "No messages"
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +We have defined this function in our kinder garden program. Did you notice that we did not call this function in our JavaScript file. Because this is a special kind of function which gets called by t
```suggestion
We have defined this function in our kindergarten program. Did you notice that we did not call this function in our JavaScript file? This is a special kind of function which gets called by the browser. It is called an event handler in JavaScript. An event handler is a function which gets called automatically by the browser and has the following characteristics:
```

2019-09-15 13:40 UTC, haraldF commented on quizzes/quiz4.md
> +Use this function when you need to generate random numbers in your code. Usually we use this function in combination with another math function Math.floor() to produce whole numbers. For example to p
```suggestion
Use this function when you need to generate random numbers in your code. Usually we use this function in combination with another math function `Math.floor()` to produce whole numbers. In order to produce numbers between 0 and 99:
```

2019-09-16 08:42 UTC, bogdanned requested changes

2019-09-16 08:42 UTC, bogdanned commented on quizzes/quiz4.md
> +### 1. Let's review the new terms we learnt in this week.
### 1. Let's review the new terms we learned in this week.

2019-09-16 11:15 UTC, sevtapim commented on quizzes/quiz4.md
> +### 1. Let's review the new terms we learnt in this week.
```suggestion
### 1. Let's review the new terms we learned in this week.
```

2019-09-17 19:15 UTC, merged